# Simple Makefile for Ren'Py PS3 using PSL1GHT

ifeq ($(strip $(PS3DEV)),)
$(error "Please set PS3DEV in your environment. e.g. /usr/local/ps3dev")
endif

include $(PS3DEV)/base_rules

# Paths
RENPY_VITA_ROOT = renpy-vita
SOURCE_DIR = $(RENPY_VITA_ROOT)/source
PYTHON_INCLUDE = $(SOURCE_DIR)/python/include/python2.7

# Target
TARGET = renpy_ps3
CONTENT_ID = RENPY0001
TITLE = RenpyPS3

# Flags
export CFLAGS	+=	-g -O2 -Wall -D__PS3__ -D__STDC_FORMAT_MACROS \
					-I$(PYTHON_INCLUDE) \
					-I$(SOURCE_DIR) -I$(SOURCE_DIR)/module \
					-I$(PS3DEV)/portlibs/ppu/include/SDL2 \
					-I$(PS3DEV)/portlibs/ppu/include

# Linker flags for wrapping core functions
WRAP_FLAGS = -Wl,--wrap=malloc -Wl,--wrap=realloc -Wl,--wrap=calloc -Wl,--wrap=free \
             -Wl,--wrap=open -Wl,--wrap=read -Wl,--wrap=write -Wl,--wrap=stat -Wl,--wrap=fstat \
             -Wl,--wrap=lseek -Wl,--wrap=close -Wl,--wrap=access -Wl,--wrap=isatty \
             -Wl,--wrap=getenv -Wl,--wrap=signal -Wl,--wrap=sigaction -Wl,--wrap=setlocale \
             -Wl,--wrap=sbrk -Wl,--wrap=gettimeofday \
             -Wl,--wrap=pthread_mutex_init -Wl,--wrap=pthread_mutex_lock -Wl,--wrap=pthread_mutex_unlock \
             -Wl,--wrap=pthread_create

export LDFLAGS	+=	-L$(SOURCE_DIR)/python/lib -L$(PS3DEV)/portlibs/ppu/lib -L$(PS3DEV)/ppu/lib \
					$(WRAP_FLAGS) \
					-lpython2.7 -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer \
					-ljpeg -lpng -lz -lm -lrt -lpthread -lvp9 -logg -lvorbis -lvorbisfile

# Sources
SOURCES_C = $(SOURCE_DIR)/main.c $(SOURCE_DIR)/ps3_stubs.c
OBJS = $(SOURCES_C:.c=.o)

all: $(TARGET).self

$(TARGET).self: $(TARGET).elf
$(TARGET).elf: $(OBJS)

clean:
	rm -f $(OBJS) $(TARGET).elf $(TARGET).self $(TARGET).pkg

.PHONY: all clean
