#---------------------------------------------------------------------------------
# Clear the implicit built in rules
#---------------------------------------------------------------------------------
.SUFFIXES:
#---------------------------------------------------------------------------------
ifeq ($(strip $(PSL1GHT)),)
$(error "Please set PSL1GHT in your environment. export PSL1GHT=<path>")
endif

include $(PSL1GHT)/ppu_rules

#---------------------------------------------------------------------------------
# TARGET is the name of the output
# BUILD is the directory where object files & intermediate files will be placed
# SOURCES is a list of directories containing source code
# INCLUDES is a list of directories containing extra header files
#---------------------------------------------------------------------------------
TARGET		:=	renpy_ps3
BUILD		:=	build
SOURCES		:=	source source/module

INCLUDES	:=	include \
				include/module \
				include/module/src \
				include/module/fribidi-src/lib

# PSL1GHT environment typically uses PORTLIBS for cross-compiled libs
ifeq ($(strip $(PORTLIBS)),)
ifneq ($(strip $(PS3DEV)),)
PORTLIBS := $(PS3DEV)/portlibs/ppu
else
PORTLIBS := $(PSL1GHT)/portlibs/ppu
endif
endif

# External Includes from PORTLIBS
PORTLIBS_INCLUDES := -I$(PORTLIBS)/include/python2.7 \
					 -I$(PORTLIBS)/include/SDL2 \
					 -I$(PORTLIBS)/include/freetype2 \
					 -I$(PORTLIBS)/include

PKGFILES	:=	../pkgfiles
ICON0		:=	$(PKGFILES)/ICON0.PNG
SFOXML		:=	../sfo.xml

TITLE		:=	RenPy PS3
APPID		:=	RENPY0001
CONTENTID	:=	UP0001-$(APPID)_00-0000000000000000

#---------------------------------------------------------------------------------
# any extra libraries we wish to link with the project
#---------------------------------------------------------------------------------
export LIBS		:=	-lpython2.7 -lSDL_image -lSDL_mixer -lSDL2 -lfreetype -lpng -ljpeg -ltiff -lz -lm -lrt -llv2 -laudio -lio -lsysutil -lsysmodule -lnet -lrsx -lgcm_sys

#---------------------------------------------------------------------------------
# list of directories containing libraries, this must be the top level containing
# include and lib
#---------------------------------------------------------------------------------
LIBDIRS	:=	$(PORTLIBS)

#---------------------------------------------------------------------------------
# no real need to edit anything past this point unless you need to add additional
# rules for different file extensions
#---------------------------------------------------------------------------------
ifneq ($(BUILD),$(notdir $(CURDIR)))
#---------------------------------------------------------------------------------

export ROOT		:=	$(CURDIR)

export OUTPUT	:=	$(ROOT)/$(TARGET)

export VPATH	:=	$(foreach dir,$(SOURCES),$(ROOT)/$(dir))

export DEPSDIR	:=	$(ROOT)/$(BUILD)

export BUILDDIR	:=	$(ROOT)/$(BUILD)

#---------------------------------------------------------------------------------
# automatically build a list of object files for our project
#---------------------------------------------------------------------------------
CFILES		:=	$(foreach dir,$(SOURCES),$(notdir ${wildcard $(ROOT)/$(dir)/*.c}))
CPPFILES	:=	$(foreach dir,$(SOURCES),$(notdir ${wildcard $(ROOT)/$(dir)/*.cpp}))
sFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(ROOT)/$(dir)/*.s)))
SFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(ROOT)/$(dir)/*.S)))

#---------------------------------------------------------------------------------
# use CXX for linking C++ projects, CC for standard C
#---------------------------------------------------------------------------------
ifeq ($(strip $(CPPFILES)),)
	export LD	:=	$(CC)
else
	export LD	:=	$(CXX)
endif

export OFILES	:=	$(CPPFILES:.cpp=.o) $(CFILES:.c=.o) \
					$(sFILES:.s=.o) $(SFILES:.S=.o)

#---------------------------------------------------------------------------------
# build a list of include paths
#---------------------------------------------------------------------------------
export INCLUDE	:=	$(foreach dir,$(INCLUDES), -I$(ROOT)/$(dir)) \
					$(PORTLIBS_INCLUDES) \
					$(LIBPSL1GHT_INC) \
					-I$(BUILDDIR)

#---------------------------------------------------------------------------------
# build a list of library paths
#---------------------------------------------------------------------------------
export LIBPATHS	:=	$(foreach dir,$(LIBDIRS),-L$(dir)/lib) \
					$(LIBPSL1GHT_LIB)

# Added -DIMG_INIT_WEBP=0 as before
export CFLAGS	:=	-O2 -Wall -D__PS3__ -DIMG_INIT_WEBP=0 -mcpu=cell -mbig-endian $(MACHDEP) $(INCLUDE)

# Linker wrapping to redirect standard calls to ps3_stubs.c
WRAPS := -Wl,--wrap=open -Wl,--wrap=open64 -Wl,--wrap=_open \
         -Wl,--wrap=read -Wl,--wrap=_read \
         -Wl,--wrap=write -Wl,--wrap=_write \
         -Wl,--wrap=lseek -Wl,--wrap=lseek64 -Wl,--wrap=_lseek \
         -Wl,--wrap=close -Wl,--wrap=_close \
         -Wl,--wrap=stat -Wl,--wrap=stat64 -Wl,--wrap=_stat \
         -Wl,--wrap=fstat -Wl,--wrap=fstat64 -Wl,--wrap=_fstat \
         -Wl,--wrap=lstat -Wl,--wrap=lstat64 -Wl,--wrap=_lstat \
         -Wl,--wrap=opendir -Wl,--wrap=readdir -Wl,--wrap=closedir \
         -Wl,--wrap=exit -Wl,--wrap=_exit -Wl,--wrap=_Exit -Wl,--wrap=abort \
         -Wl,--wrap=gettimeofday \
         -Wl,--wrap=malloc -Wl,--wrap=free -Wl,--wrap=realloc -Wl,--wrap=calloc \
         -Wl,--wrap=signal -Wl,--wrap=sigaction -Wl,--wrap=raise -Wl,--wrap=kill \
         -Wl,--wrap=isatty -Wl,--wrap=getenv -Wl,--wrap=getcwd -Wl,--wrap=chdir \
         -Wl,--wrap=fflush -Wl,--wrap=fcntl -Wl,--wrap=ioctl -Wl,--wrap=__assert_fail \
         -Wl,--wrap=setlocale -Wl,--wrap=getuid -Wl,--wrap=getgid -Wl,--wrap=geteuid -Wl,--wrap=getegid \
         -Wl,--wrap=getpid -Wl,--wrap=getppid -Wl,--wrap=pipe -Wl,--wrap=symlink \
         -Wl,--wrap=fdatasync -Wl,--wrap=ttyname -Wl,--wrap=execv -Wl,--wrap=readlink \
         -Wl,--wrap=gethostname -Wl,--wrap=sysconf -Wl,--wrap=__assert

export LDFLAGS	:=	-finline-limit=5000 -Wl,--gc-sections -s -Wl,--strip-all -Wl,--sort-common=descending $(MACHDEP) -Wl,-Map,$(notdir $@).map $(WRAPS)

export OUTPUT	:=	$(CURDIR)/$(TARGET)
.PHONY: $(BUILD) clean

#---------------------------------------------------------------------------------
$(BUILD):
	@[ -d $@ ] || mkdir -p $@
	@$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile.ps3

#---------------------------------------------------------------------------------
clean:
	@echo clean ...
	@rm -fr $(BUILD) *.elf *.self *.pkg

#---------------------------------------------------------------------------------
pkg:	$(BUILD) $(OUTPUT).pkg

#---------------------------------------------------------------------------------
else

DEPENDS	:=	$(OFILES:.o=.d)

#---------------------------------------------------------------------------------
# main targets
#---------------------------------------------------------------------------------
all: $(OUTPUT).self

$(OUTPUT).self: $(OUTPUT).elf

$(OUTPUT).elf:	$(OFILES)
	$(LD) $(OFILES) $(LIBPATHS) $(LIBS) $(LDFLAGS) -o $@

-include $(DEPENDS)
#---------------------------------------------------------------------------------
endif
#---------------------------------------------------------------------------------
